//! Génère fixtures/reference_mfcc.json depuis Rust directement.
//! Usage: cargo run --example generate_fixture --features standalone

use std::fs;
use pipeline_dsp::pipeline_dsp::{config::DspConfig, pipeline::DspPipeline};

fn main() {
    let sample_rate = 16_000usize;
    let duration_s = 1usize;
    let n_samples = sample_rate * duration_s;
    let freq = 440.0_f32;
    let samples: Vec<f32> = (0..n_samples)
        .map(|i| (2.0 * std::f32::consts::PI * freq * i as f32 / sample_rate as f32).sin())
        .collect();

    let cfg = DspConfig::default();
    let mut pipeline = DspPipeline::new(cfg).unwrap();
    let matrices = pipeline.process_batch(&samples);

    assert!(!matrices.is_empty(), "No matrices produced");
    let first = &matrices[0];
    let n_frames = first.len(); // 98

    // Build JSON manually (no serde dep in main crate)
    let mut mfcc_json = String::new();
    mfcc_json.push('[');
    for (t, frame) in first.iter().enumerate() {
        mfcc_json.push('[');
        for (k, &v) in frame.iter().enumerate() {
            mfcc_json.push_str(&format!("{}", v));
            if k < 12 { mfcc_json.push(','); }
        }
        mfcc_json.push(']');
        if t < n_frames - 1 { mfcc_json.push(','); }
    }
    mfcc_json.push(']');

    let output = format!(
        r#"{{
  "_comment": "Generated by examples/generate_fixture.rs — do not modify manually. Ground truth from Rust vDSP pipeline.",
  "sample_rate": {},
  "n_frames": {},
  "n_mfcc": 13,
  "freq_hz": {},
  "mfcc": {}
}}"#,
        sample_rate, n_frames, freq, mfcc_json
    );

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/reference_mfcc.json");
    fs::write(path, &output).unwrap();
    println!("✅ {} frames × 13 MFCC → {}", n_frames, path);
    println!("   Frame 0[:4]: {:?}", &first[0][..4]);
}
